### ISSUE TITLE
Player.Close causes infinite recursion

### ISSUE THREAD

**Issue by jchv** [leberKleber/go-mpris#5]
`Player.Close()` calls `Player.connection.Close` which calls `dbusConnWrapper.Close` which accidentally calls `dbusConnWrapper.Close` instead of `dbusConnWrapper.conn.Close`.

https://github.com/leberKleber/go-mpris/blob/aca50e1f981a66fb1d3936ef1d0b883fe4e726f1/dbus-wrapper.go#L49-L51

I imagine this is meant to be `return w.conn.Close()`?

**Comment by leberKleber** [comment]
Hey @jchv,
thanks for your participation. You're absolutely right. I will fix this soon.

**Comment by jchv** [comment]
Thanks!
