### ISSUE TITLE
Go Doc pushes to unpublished version. 

### ISSUE THREAD

**Issue by duckbrain** [leberKleber/go-mpris#8]
The GoDoc really wants to default to v1.1.0. It appears the tag has been deleted, but the version is still cached in the module cache.

I suspect the GoDoc would be fixed if you issue a retraction. At the least, that would fix `go get -u` to get the actual latest.

https://go.dev/ref/mod#go-mod-file-retract

Add to the go.mod

```
retract (
    v1.1.0
    v1.1.1
)
```

and tag that as `v1.1.1` and clone it through the module cache.

**Comment by leberKleber** [comment]
Hey,
thanks for your contribution. Has been fixed in #9.

Happy Christmas;

Greetings

**Comment by leberKleber** [comment]
Hey,
thanks for your contribution. Has been fixed in https://github.com/leberKleber/go-mpris/pull/9.

Happy Christmas;

Greetings
